@startuml


class TimeoutCounter {
'  #app_ : Application&
}

'TimeoutCounter o-- "1" Application 
': app_

class Application {
  -m_ledgerReplayer : uptr<LedgerReplayer>
'  -m_inboundLedgers : uptr<InboundLedgers>
  -m_ConsensusSync : uptr<ConsensusSync>
}

Application *-- "1" LedgerReplayer 
': m_ledgerReplayer
'Application *-- "1" InboundLedgers 
': m_inboundLedgers

'Application "1" --o InboundLedgers 
': app_

'class InboundLedgers {
'  -app_ : Application&
'}

'InboundLedgers "1" --o LedgerReplayer 
': inboundLedgers_
'Application "1" --o LedgerReplayer 
': app_

note "LedgerMaster is omited in the classes.\nBut the local ledger is queried before any downloads.\nInboundLedgers is omited in the classes.\nBut it is the fallback mechanism of all downloads." as N1

class LedgerReplayer {
  +replay(startLedgerHash, finishLedgerHash, reason)
  +replay(finishLedgerHash, numLedgers, reason)
  +optional<RCLValidatedLedger> acquireExtendedHeader(ledgerHash) 
  +sweep()
'  -app_ : Application&
'  -inboundLedgers_ : InboundLedgers&
  -tasks_ : vector<sptr<LedgerReplayTask>>
  -deltas_ : hash_map<u256, wptr<LedgerDeltaAcquire>>
  -skipLists_ : hash_map<u256, wptr<SkipListAcquire>>
  -extendedHeaders_ : aged_hash_map<u256, sptr<ExtendedHeader>
}
'note top of SkipListAcquire : Extend SkipListAcquire to ExtendedHeader.

note left of LedgerReplayer::extendedHeaders_
  extendedHeader cache
end note

note left of LedgerReplayer::replay
  ConsensusSync calls it
  after get start ledger
end note

note left of LedgerReplayer::acquireExtendedHeader
  RCLValidations calls it
  for preferred branch algo
end note

LedgerReplayer *-- "n" LedgerReplayTask 
': tasks_
'LedgerReplayer o-- LedgerDeltaAcquire 
': deltas_
'LedgerReplayer o-- SkipListAcquire 
': skipLists_

TimeoutCounter <.. LedgerReplayTask
'InboundLedgers "1" --o LedgerReplayTask 
': inboundLedgers_
'LedgerReplayer "1" --o LedgerReplayTask 
': replayer_

class LedgerReplayTask {
'  -inboundLedgers_ : InboundLedgers&
'  -replayer_ : LedgerReplayer&
  -skipListAcquirers_ : vector<sptr<SkipListAcquire>>
  -deltas_ : vector<sptr<LedgerDeltaAcquire>>
'  +addDelta(sptr<LedgerDeltaAcquire>)
  +init()
  +canMergeInto()
}

LedgerReplayTask "n" *-- "n" SkipListAcquire 
': skipListAcquirer_

note left of LedgerReplayTask::skipListAcquirers_
  extened to support
  skiplist concatenation
end note

LedgerReplayTask "n" *-- "n" LedgerDeltaAcquire 
': deltas_

TimeoutCounter <.. SkipListAcquire
'InboundLedgers "1" --o SkipListAcquire 
': inboundLedgers_
'LedgerReplayer "1" --o SkipListAcquire 
': replayer_
'LedgerReplayTask --o SkipListAcquire : implicit via callback

class SkipListAcquire {
  +addDataCallback(callback)
  +init()
'  -inboundLedgers_ : InboundLedgers&
'  -replayer_ : LedgerReplayer&
  -dataReadyCallbacks_ : vector<callback>
}

TimeoutCounter <.. LedgerDeltaAcquire
'InboundLedgers "1" --o LedgerDeltaAcquire 
': inboundLedgers_
'LedgerReplayer "1" --o LedgerDeltaAcquire 
': replayer_
'LedgerReplayTask --o LedgerDeltaAcquire : implicit via callback

class LedgerDeltaAcquire {
  +addDataCallback(callback)
  +init()
'  -inboundLedgers_ : InboundLedgers&
'  -replayer_ : LedgerReplayer&
  -dataReadyCallbacks_ : vector<callback>
}

Application *-- "1" ConsensusSync
'Application "1" --o ConsensusSync
class ConsensusSync #lightGreen {
  +syncToLedger(ledgerHash)
  -cdnLedgers_ : CDNLatestFlagLedgers 
'  -inboundLedgers_ : InboundLedgers&
  -replayer_ : LedgerReplayer&
}

TimeoutCounter <.. CDNLatestFlagLedgers
ConsensusSync *-- "1" CDNLatestFlagLedgers
'ConsensusSync "1" --o CDNLatestFlagLedgers
class CDNLatestFlagLedgers #lightGreen {
  +download(CDN_address)
}

TimeoutCounter <.. ExtendedHeaderTask
LedgerReplayer *-- "n" ExtendedHeaderTask
ExtendedHeaderTask "1" *-- "1" SkipListAcquire 
class ExtendedHeaderTask #lightGreen {
  -data_ : sptr<SkipListAcquire>  
  +init()
}


@enduml