@startuml

'note bottom of Application : "LedgerMaster is omited in the classes. But the\nlocal ledger cache is queried before any downloads." as N1

'note as N1 
'  LedgerMaster is omited in the classes. 
'  But the local ledger cache is queried before any downloads.
'  InboundLedgers is omited in the classes. 
'  But it is the fallback mechanism of all downloads.
'end node

class TimeoutCounter {
'  #app_ : Application&
}

'TimeoutCounter o-- "1" Application 
': app_


class Application {
  -m_ledgerReplayer : uptr<LedgerReplayer>
'  -m_inboundLedgers : uptr<InboundLedgers>
  -m_ConsensusSync : uptr<ConsensusSync>
}

Application *-- "1" LedgerReplayer 
': m_ledgerReplayer
'Application *-- "1" InboundLedgers 
': m_inboundLedgers

'Application "1" --o InboundLedgers 
': app_

'class InboundLedgers {
'  -app_ : Application&
'}

'InboundLedgers "1" --o LedgerReplayer 
': inboundLedgers_
'Application "1" --o LedgerReplayer 
': app_

note "LedgerMaster is omited in the classes.\nBut the local ledger cache is queried before any downloads.\nInboundLedgers is omited in the classes.\nBut it is the fallback mechanism of all downloads." as N1

class LedgerReplayer {
  +replayTo(finishLedgerHash, numLedgers, reason)
  +replayFromTo(startLedgerHash, finishLedgerHash, reason)
  +acquireExtendedHeader(ledgerHash) 
  -app_ : Application&
'  -inboundLedgers_ : InboundLedgers&
  -tasks_ : vector<sptr<LedgerReplayTask>>
  -deltas_ : hash_map<u256, wptr<LedgerDeltaAcquire>>
  -skipLists_ : hash_map<u256, wptr<SkipListAcquire>>
  -extendedHeaders_ : hash_map<u256, sptr<ExtendedHeader>
}
'note top of SkipListAcquire : Extend SkipListAcquire to ExtendedHeader.

note left of LedgerReplayer::replayFromTo
  ConsensusSync calls it
  after get start ledger
end note

note left of LedgerReplayer::acquireExtendedHeader
  RCLValidations calls it
  for preferred branch algo
end note

LedgerReplayer *-- LedgerReplayTask 
': tasks_
'LedgerReplayer o-- LedgerDeltaAcquire 
': deltas_
'LedgerReplayer o-- SkipListAcquire 
': skipLists_

TimeoutCounter <.. LedgerReplayTask
'InboundLedgers "1" --o LedgerReplayTask 
': inboundLedgers_
'LedgerReplayer "1" --o LedgerReplayTask 
': replayer_

class LedgerReplayTask {
'  -inboundLedgers_ : InboundLedgers&
'  -replayer_ : LedgerReplayer&
  -skipListAcquirer_ : vector<sptr<SkipListAcquire>>
  -deltas_ : vector<sptr<LedgerDeltaAcquire>>
'  +addDelta(sptr<LedgerDeltaAcquire>)
  +init()
}

LedgerReplayTask *-- "n" SkipListAcquire 
': skipListAcquirer_
LedgerReplayTask *-- "n" LedgerDeltaAcquire 
': deltas_

TimeoutCounter <.. SkipListAcquire
'InboundLedgers "1" --o SkipListAcquire 
': inboundLedgers_
'LedgerReplayer "1" --o SkipListAcquire 
': replayer_
'LedgerReplayTask --o SkipListAcquire : implicit via callback

class SkipListAcquire {
  +addDataCallback(callback)
  +init()
'  -inboundLedgers_ : InboundLedgers&
'  -replayer_ : LedgerReplayer&
  -dataReadyCallbacks_ : vector<callback>
}

TimeoutCounter <.. LedgerDeltaAcquire
'InboundLedgers "1" --o LedgerDeltaAcquire 
': inboundLedgers_
'LedgerReplayer "1" --o LedgerDeltaAcquire 
': replayer_
'LedgerReplayTask --o LedgerDeltaAcquire : implicit via callback

class LedgerDeltaAcquire {
  +addDataCallback(callback)
  +init()
'  -inboundLedgers_ : InboundLedgers&
'  -replayer_ : LedgerReplayer&
  -dataReadyCallbacks_ : vector<callback>
}

Application *-- "1" ConsensusSync
'Application "1" --o ConsensusSync
class ConsensusSync #lightGreen {
  +syncToLedger(ledgerHash)
  -cdnLedgers_ : CDNLatestFlagLedgers 
'  -inboundLedgers_ : InboundLedgers&
  -replayer_ : LedgerReplayer&
}

TimeoutCounter <.. CDNLatestFlagLedgers
ConsensusSync *-- "1" CDNLatestFlagLedgers
'ConsensusSync "1" --o CDNLatestFlagLedgers
class CDNLatestFlagLedgers #lightGreen {
  +download(CDN_address)
}

TimeoutCounter <.. ExtendedHeaderTask
LedgerReplayer *-- ExtendedHeaderTask
ExtendedHeaderTask *-- "1" SkipListAcquire 
class ExtendedHeaderTask #lightGreen {
  -data_ : sptr<SkipListAcquire>  
  +init()
}


@enduml