@startuml negativeUNL_highLevel_sequence

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 160

actor "Rippled Start" as RS
participant "NetworkOPs" as NOP 
participant "Consensus\nRCLConsensus" as C
participant "Validations\nRCLValidationsAdaptor" as V 
participant "LedgerMaster" as LM
participant "InboundLedgers" as IL #lightgreen
actor "Timer" as T
actor "Network" as N

== Case: consensus start ==

RS -> RS: load ledger or\nstart genesis ledger
RS -> NOP: beginConsensus 
hnote over NOP: later beginConsensus call will be by\nendConsensus when rounds end
activate NOP
NOP -> C: startRound 
activate C
alt network closed ledger != our previous ledger
C -[#green]> IL: <font color=green>acquire network closed ledger if don't have
hnote over C: the network closed ledger\ncould be the preferred ledger\nas in **Case: consensus end** 
end
deactivate C
deactivate NOP

== Case: every second ==

T -> C: checkLedger
activate C
C -> V: getPreferred
activate V
V -> C: preferred ledger hash if any
deactivate V 
alt network closed ledger != our previous ledger
C -[#green]> IL: <font color=green>acquire network closed ledger if don't have
end
deactivate C 

== Case: new validation message ==

N -> NOP: recvValidation
activate NOP
NOP -> V: handleNewValidation
deactivate NOP

activate V
V -> V: add to validations
alt current and trusted
V -> V: updateTrie
'alt don't have the ledger
hnote over V #Red: **acquire ledger header instead of ledger**
V -[#green]> IL: <font color=green>acquire ledger if don't have
'end
V -> LM: checkAccept
activate LM
deactivate V
alt check seq
'alt don't have the ledger
LM -[#green]> IL: <font color=green>acquire ledger if don't have
hnote over LM #Red: **This case can be removed.**\nTo be safe, only acquire if\nnumTrustedForLedger >= X%
end
hnote over LM: checkAccept is also called by\nLedgerMaster::consensusBuilt in\n**Case: consensus build ledger**
end
deactivate LM 

== Case: consensus build ledger ==

C -> LM: consensusBuilt
activate LM
alt ledger built cannot be fully validated
hnote over LM: maybe we saved up validations for some\nother ledger that can be fully validated
LM -> V: get currentTrusted
V -> LM: Validations
alt validations of a ledger >= quorum
LM -> LM: checkAccept
alt check seq
'alt don't have the ledger
LM -[#green]> IL: <font color=green>acquire ledger if don't have
hnote over LM #Red: **This case can be removed.**\nTo be safe, only acquire if\nnumTrustedForLedger >= X%
'end
end
end
end
deactivate LM
== Case: consensus end ==

'activate C
'hnote over C: consensus round\ndone, ledger built
C -> NOP: endConsensus
'deactivate C

activate NOP
NOP -> NOP: checkLastClosedLedger
NOP -> V: getPreferredLCL
activate V
V -> NOP: preferred ledger hash if any
deactivate V
alt preferred ledger != our ledger
NOP -[#green]> IL: <font color=green>acquire preferred ledger if don't have
end
deactivate NOP

@enduml
