[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
categories = ["command-line-utilities", "development-tools", "development-tools::testing", "wasm"]
version = "0.1.0"
description = "A WebAssembly test case generator"
documentation = "https://docs.rs/wasm-smith"
edition = "2024"
license = "Apache-2.0"
name = "wasm-smith"
readme = "./README.md"
repository = "https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-smith"
exclude = ["/benches/corpus"]

[package.metadata.docs.rs]
all-features = true

[[bench]]
name = "corpus"
harness = false


[dependencies]

anyhow = "1.0.100"
arbitrary = { version = "1.4.2", features = ["derive"] } 
clap = { version = "4.5.54", optional = true }
flagset = "0.4.7"
serde = { version = "1.0.228", optional = true }
serde_derive = { version = "1.0.228", optional = true }
wasm-encoder = { version = "0.244.0", features = ["std"] }
wasmparser = { version = "0.244.0", optional = true, features = ["std", "validate", "features", "simd"] }
wat = { version = "1.244.0", optional = true }

[features]
_internal_cli = ["clap", "serde", "dep:wasmparser", "dep:wat"]
wasmparser = ['dep:wasmparser', 'wasm-encoder/wasmparser']
component-model = ['wasm-encoder/component-model']
serde = ['dep:serde', 'dep:serde_derive', 'flagset/serde', 'dep:wat']
clap = ["dep:clap"]
